spring.application.name=ecom-application

spring.datasource.url=jdbc:mysql://localhost:3306/ecom_db
spring.datasource.username=root
spring.datasource.password=Praveen@2004

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=*



#spring:
#    application:
#        name: ecom-application
#    h2:
#        console:
#            enabled: true
#    datasource:
#        url: jdbc:h2:mem:test
#    jpa:
#      show-sql:
#        true
#      hibernate:
#        ddl-auto:
#          create